### ISSUE TITLE
Use scala code format tool (in CI) 

### ISSUE THREAD

**Issue by paulo-coutinho** [cross-language-cpp/djinni-generator#100]
Hi,

My suggestion is to use a scala format tool, like this:

- https://scalameta.org/scalafmt/
- https://github.com/scalameta/scalafmt

It will make the code more clear and easy to do maintenance.

Thanks.

**Comment by a4z** [comment]
yes :-) 

however, how to integrate that, 
as github (pre) commit hooks
integrating it into sbt 
something different 

ideas welcome
