### ISSUE TITLE
Bring Snapchat things to our main repository

### ISSUE THREAD

**Issue by paulocoutinhox** [cross-language-cpp/djinni-generator#103]
Hi,

I talked to "Li Feng", the engineer from Snapchat that is responsible for Djinni on Snapchat to understand all modifications that they do in Djinni source and all the new features added.

I think that it is too much relevant, because will speed up somethings (like strings), have some general fixes and will add support for more field types (like transfer pointers/ownership between languages).

I will bring the source code and the cross-language-cpp guys can check the pull-request slowly as i bring it to our repository.

The Snapchat repository is here:
https://github.com/Snapchat/djinni

The Snapchat article is here:
https://eng.snap.com/improving_djinni

Some modifications that i collect from their README:

 - Replaced sbt and gyp with Bazel
 - Added move assigment operator to GlobalRef in all djinni_support.hpp files
 - Made JniClassInitializer constructor public to allow arbitrary additional initialization in JNI_OnLoad()
 - Speed up string passing between Java and C++ (about 5-10x faster depending on string size)
 - Eliminate CppProxy finalizers (better stability)
 - Injecting code with `DJINNI_FUNCTION_PROLOGUE`
 - Option to generate ObjC protocols
 - Option to generate function prologue
 - Option to omit objc helper methods
 - Option to disable exception translation in ObjC
 - array<> type support
 - outcome<> type support
 - Protobuf type support
 - Local flags with `@flag` directive
 - DataView for copy free data passing
 - DateRef for copy free data passing with ownership
 - Bug fixes

What do you think?

**Comment by a4z** [comment]
I will transfer this issue into a discussion item, since there is no definition of done possible, and I see that there are various details to discuss for some points on the list.
So we will keep that as a discussion, from which issues to implement can arise .
