### ISSUE TITLE
enums, records and possible others, should not be generated in uppercase but as written in the IDL file

### ISSUE THREAD

**Issue by a4z** [cross-language-cpp/djinni-generator#11]
As a user, I want that my enums, records and other entities are generated as specified in the djinni idl file, and not be converted into uppercase letters.

Origin: 
https://github.com/cross-language-cpp/djinni-intellij-plugin/issues/18

**Comment by a4z** [comment]
This name generation can  be controlled via the `--ident-java-enum` command line option, like all (most) other naming can be controlled via such options.

For file names that is for sure a good idea, for something like enum values, I do not know ...

There seems to be no option that says, do not convert that text, it goes through some conversion. 
And that feels like unwanted feature creep.

So fixing/improving that would be, finding an option to let` text in - text out` happen

Until we fix that, please use the `--ident-java-enum` and see if any of ``FooBar`, `fooBar`, `foo_bar`, `FOO_BAR`, `m_fooBar`` gives you better results than you have now.

**Comment by a4z** [comment]
The `foo_bar` style is the style that does not convert anything. So if you want to avoid conversions, use this option in the corresponding `--ident-*` arguments.

We could change that, and I know how, and I thing we should, since the default should give users the least surprise, and not the pre configured coding stile from the original authors.

However, this would be a breaking change also, so we need to think a little bit more about that.

Either starting to version the idl files, or having an additional flag that selects the default behaviour ... 
Feedback is welcome!

**Comment by jothepro** [comment]
So if one chooses the `foo_bar` option, there will be no conversion of identifiers, no matter if they are TrainCase, camelCase, ...? That's weird. 
I'd prefer improving the documentation on this instead of changing anything that may break someones code.

**Comment by jothepro** [comment]
Setting `foo_bar` as default option sounds like a reasonable workaround. 👍

**Comment by a4z** [comment]
We can actually break the default behaviour if we provide the `--whatever-option value` that restore the previous behaviour.
So users will have an easy way to not break existing generated code by copy and past a string. 

I think this is the way to go, but we should test it with #14 first
So I will implement it there, since this has zero impact for users.
And based on that we can communicate this kind of flag change.

Then we can announce the upcoming flag change and see if we get any feedback.
That way is not as fast as I would like to have it, but I do not want to annoy potential or actual users.

**Comment by a4z** [comment]
Solved via #24 and #28, all settings are configurable by a user and documented now
