### ISSUE TITLE
Support for ARM pointer tagging

### ISSUE THREAD

**Issue by davidschreiber** [cross-language-cpp/djinni-generator#110]
Recently, our team ran into a Djinni issue that started with bumping the target SDK version of our Android library to 30. On ARM devices, this triggered crashes which we could successfully backtrace to Android's new pointer tagging functionality: https://source.android.com/devices/tech/debug/tagged-pointers

Disclaimer: We're not yet using this version of Djinni, but are using an older fork of the original project. 

Do you know if pointer tagging is already working on this project, or do you plan to support it in future versions?

**Comment by a4z** [comment]
As discussed in https://github.com/cross-language-cpp/djinni-support-lib/issues/30 , it seems we already fixed that issue in the support-lib.
Therefore I close this issue. Please feel free to reopen if you think there is more to that topic.

In any case, thanks a lot for the link to the tagged pointer docs! I haven't seen that so far
