### ISSUE TITLE
Objective-C generated objects should conform to NSObject protocol

### ISSUE THREAD

**Issue by ngmeyer** [cross-language-cpp/djinni-generator#117]
See best practices document from Apple here: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithProtocols/WorkingwithProtocols.html

As an example not conforming to NSObject protocol results in build errors if we attempt to get the class from the protocol e.g.:

for (id<ABCGeneratedType> thing in things) {
  NSString *className = NSStringFromClass([thing class]);  // build error
  ...
}

**Comment by a4z** [comment]
Since the PR was merged, we can close that issue as solved
