### ISSUE TITLE
Pure C generator

### ISSUE THREAD

**Issue by paulo-coutinho** [cross-language-cpp/djinni-generator#126]
Hi,

The C Wrapper Generator still depends on python something:
https://github.com/cross-language-cpp/djinni-generator/blob/main/src/main/scala/djinni/CWrapperGenerator.scala

Can it be removed?

Parts:

![image](https://user-images.githubusercontent.com/395096/148286319-586b9e9c-a4b6-48ea-828e-4c98a8661944.png)

![image](https://user-images.githubusercontent.com/395096/148286347-27b70f67-38d3-451c-aa98-6e901daca6f9.png)

![image](https://user-images.githubusercontent.com/395096/148286385-289514d5-2219-4e98-89a3-a79230d7c289.png)

![image](https://user-images.githubusercontent.com/395096/148286415-6001a6f8-da12-45f4-92ca-90938944b13b.png)

![image](https://user-images.githubusercontent.com/395096/148286442-eccf94c2-9503-419e-a456-6667b5d0b374.png)

**Comment by a4z** [comment]
Hi Paulo, 
if you open a source file in github, and click on the line number, 3 dots `...` will appear left to the line number.
There you can select the `copy permalink` option to refer to a certain line, or block, of code.
This is way better than screenshoots, please consider using that in future to point to code.

On the main topic:  
The code you refer to adds just comment that is used by PyCFFI to ignore stuff
It does not add python specific C code, just  a `// python_cdef_ignore` comment at the end of the line 
So, while this is kind of python specific, it's also not python specific :-) 

Is there any special reason why you think this is disturbing anything ?

**Comment by paulo-coutinho** [comment]
Sorry for the images.

No, i don't see what was generated, so it's my mystake, sorry.

The comment is not a problem.

Thanks more one time.

**Comment by a4z** [comment]
No need to apologise Paulo, there is a lot of functionality in github I also do not know. 
and for those I do know, I often needed someone to tell me that it exits or how it works. 
And the same is with the djinni code base, every time I look at it I find something new.
