### ISSUE TITLE
Recent change for all protocols to be based on NSObject add additional restriction on swift use.

### ISSUE THREAD

**Issue by eakoli** [cross-language-cpp/djinni-generator#133]
This PR https://github.com/cross-language-cpp/djinni-generator/pull/118# updated the genreated @protocol for

```
callback = interface +o { 
   ...
}
```

from this

```
@protocol callback {
   ....
}
```

to this

```
@protocol callback <NSObject> {
   ....
}
```

When using djinni to integrate with objc its not much of an issue. But, when the target consumer is Swift, it adds an additional requirement that the swift objects be NSObjects, which limits what swift objects can implement the protocol.

Previously we were using generator 1.1.0 to generate an interface consumed exclusively by swift code. Once we updated to 1.3.0, we had to go change the derivation of every swift object implementing an interface from djinni to derive from NSObject. In some cases we had to rework the code as the class originally implementing the interface was derived from an object that we don't control the source for, so we had to switch to a light object that implemented the interface an delegated to the actual object that had the implementation.

I would propose that there is a way to disable the <NSObject> requirement. 

Maybe its auto-disabled when `--objc-swift-bridging-header` is defined, as the purpose of that switch is to generate an interface importable by swift.

Or a new switch `--objc-strict-protocols` that when ON enables this functionality.

**Comment by jothepro** [comment]
I can confirm that this requirement in Swift can be annoying, without giving any benefit (at least to me). I like the idea of adding a switch to disable it. 👍

**Comment by a4z** [comment]
Thanks for bringing this issue up! 
Generally speaking, I do not like more flags, since we have already too many, but think this one is unavoidable, at least, I do not have any idea ... (except extending the IDL, what might be even a bad idea...)

**Comment by eakoli** [comment]
@a4z Yea, it would be nice to be able to explictly set a base for things, but that does add soo many levels of complexity.

ideally....if we had a direct to swift generator.... =P

**Comment by LiFengSC** [comment]
It seems the benefit of having <NSObject> in ObjC code isn't that much big of a deal. So why not just get rid of it?

When it was added, we assumed all objects were already NSObjects, which is true in pure ObjC, so adding that doesn't require the implementation side to do anything extra. But now we know Swift objects are not NSObjects by default.

From my experience of using Djinni at Snap, I don't remember any use case where being protocols being NSObjects is critical to the user code. I think all our code still compiles without any change when <NSObject> is taken out.

**Comment by a4z** [comment]
The NSObject protocol implementation was requested by a user, please see #118  
Therefore , too revert this, we need to  sync with @ngmeyer , and maybe others who now relay on that behaviour.

For this project, it's hard to please all users. If your audience / user base is only your company, as in the snapchat fork, it's easy to do such changes. We need to be more careful.

I am again hit by the fact how hard it is to 
a) preserve and maintain the original djinni implementation, 
and
b) enable development , the addition of new features and evolve over time

in a general purpose project where you do not know who uses it, and whom's work you will break with changes like that

**Comment by a4z** [comment]
I added a PR suggestion that might fix that issue, please review and leave comments, 
please see #134
