### ISSUE TITLE
32 bit flag to enum generation issue

### ISSUE THREAD

**Issue by martin00001313** [cross-language-cpp/djinni-generator#142]
In case of defining flags which later are translated to 32 bit unsigned enum, for the 32th enum value issue is occurred as '1<<31' is considered signed i32 operation and is overflow.
Instead, by generating with unsigned postfix 'u', i.e. '1u<<31' will work fine.

Proposal, use '1u<<shift' instead of '1 << shift'. Both C++ and ObjC support it fine

**Comment by a4z** [comment]
Thank you for the report @martin00001313 !

Please feel free to add you as review to #143 , what will hopefully fix this isse

**Comment by a4z** [comment]
If you need a fix already today, you can use the [Latest development build](https://github.com/cross-language-cpp/djinni-generator/releases/tag/current-latest) that was just generated
