### ISSUE TITLE
Add @SuppressWarnings("deprecation") annotation to generated finalize methods

### ISSUE THREAD

**Issue by richey-v** [cross-language-cpp/djinni-generator#16]
The use of `finalize` is a big can of worms (see StackOverflow [Why is the finalize() method deprecated in Java 9?](https://stackoverflow.com/questions/56139760/why-is-the-finalize-method-deprecated-in-java-9)), but it would be nice to at least have a djinni option to have the generated Java classes annotate the `finalize` generated methods with `@SuppressWarnings("deprecation")` so I don't get Java compile warnings.

**Comment by a4z** [comment]
I wonder if there is an alternative to use `finalize` .
Didn't find one, but I am also not a java expert so chances I have overseen something are huge

**Comment by Znerole** [comment]
I think the correct way to handle this would be to use [PhantomReferences](https://docs.oracle.com/javase/8/docs/api/java/lang/ref/PhantomReference.html).

See also here: https://www.baeldung.com/java-phantom-reference

I've implemented something like this many moons ago, but I really don't remember any details.
