### ISSUE TITLE
Evaluate hiennguyenle/finn fork

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-generator#17]
@prsolucoes has mentioned this fork of djinni:
https://github.com/hiennguyenle/finn

A a first glance it seems very active & miles ahead in terms of features.

As a maintainer I want to evaluate the improvements. To list some awesome features that have been added to the generator:
- Deprecated Directive
- Extend Record
- a swift generator

Given that the advancements match with our idea of djinni, I'd like to get in contact with the maintainer if . Maybe we can collaborate in some way.

**Comment by paulo-coutinho** [comment]
Yes, im use it and is working, but it has features for the maintainer.

I forked it and remove json things, because need use a json library that require c++17.

The other fixes works without problem.

**Comment by a4z** [comment]
ok, I became active that way, since I have no better idea how to reach the author 
https://github.com/hiennguyenle/compression-log-handler/issues/1
lets see what will happen ...

But I think I can close that issue now. A continuation of that topic might fit into the  discussion section, but if anyone has a different opinion, pls let me know .

**Comment by mutagene** [comment]
It's a pity this didn't work out. For me, I could certainly take advantage of generated json serialisers - something I'm currently doing a lot by hand with the djinni-generated types.

**Comment by a4z** [comment]
Well, @mutagene , you can try to contact the author and see if you get any response, I tried, and did not get any, but maybe you have more luck.

Please also note that even if this ticket is closed, there is still an _active_ topic on our discussion board.
see: https://github.com/cross-language-cpp/djinni-generator/discussions/73 

Everything else on the topic please there.
