### ISSUE TITLE
Recommendation:  document how Djinni comments generate Doxygen / Javadoc

### ISSUE THREAD

**Issue by richey-v** [cross-language-cpp/djinni-generator#18]
I was very pleased to discover that Djinni generated Javadoc / Doxygen friendly documentation from the .djinni file comments.  In fact, this was a big "selling point" in favor of using Djinni.

**Comment by jothepro** [comment]
Some questions to make my work easier:
- Afaik all it does is put the comments from the idl on top of classes/properties. I didn't know this was somewhat special. Which other tools did you evaluate that did not offer this feature? 
- Maybe it does even more and I don't know about it. Can you provide a small example snippet? (djinni interface with comments + how it turns out in Java/C++ code?)

**Comment by richey-v** [comment]
Sure... here's a small example.  After Djinni generates the Java and Obj-C, I run each through Doxygen and get nice documentation.

Djinni IDL:
```
# Structure for a single accelerometer sample
AccelerometerSample = record {
  # X-axis signed 32-bit value
  x: i32;

  # Y-axis signed 32-bit value
  y: i32;
  
  # Z-axis signed 32-bit value
  z: i32;
} 
```

Generated Java (note the `/** */` instead of just `/* */`):
```Java

/** Structure for a single accelerometer sample */
public class AccelerometerSample {

    /** X-axis signed 32-bit value */
    public int getX() {
        return x;
    }

    /** Y-axis signed 32-bit value */
    public int getY() {
        return y;
    }

    /** Z-axis signed 32-bit value */
    public int getZ() {
        return z;
    }
}
```


Generated Objective-C (note the `/** */` instead of just `/* */`):
```objective-c
/** Structure for a single accelerometer sample */
@interface VALAccelerometerSample : NSObject

/** X-axis signed 32-bit value */
@property (nonatomic, readonly) int32_t x;

/** Y-axis signed 32-bit value */
@property (nonatomic, readonly) int32_t y;

/** Z-axis signed 32-bit value */
@property (nonatomic, readonly) int32_t z;
```

**Comment by richey-v** [comment]
Also, Doxygen automatically cross-links the types which is very cool (no good example handy, sorry).

Doxygen annotations can be added, too, in the case that Doxygen doesn't automatically cross-link:

Djinni IDL:
```
TrimType = enum {
  DRIVE;
  GAIN;
  NUM_TYPES;
}

TrimConfig = record {
  # list of TrimLimit, indexed by TrimType
  # (length of list shall be @ref TrimType::NUM_TYPES)
  limits: list<TrimLimit>;
} 
```

Generated Java (note the `NUM_TYPES`):
```Java
    /**
     * list of TrimLimit, indexed by TrimType
     * (length of list shall be @ref TrimType::NUM_TYPES)
     */
    public ArrayList<TrimLimit> getLimits() {
        return limits;
    }
```

Doxygen HTML, pasted here as plaintext:
```
list of TrimLimit, indexed by TrimType (length of list shall be TrimType.NUM_TYPES)
```

**Comment by richey-v** [comment]
Please do not use these examples directly in the Djinni documentation!

**Comment by jothepro** [comment]
Of course not. I just wanted to make sure I didn't miss something 👍

**Comment by jothepro** [comment]
I've added a block about comments and their compatibility with doxygen a while ago. I think this issue is resolved with that:
https://djinni.xlcpp.dev/djinni-generator/idl/#comments

If you'd like to see more details about how comments work, pls re-open this issue or make a suggestion in a PR :)

**Comment by richey-v** [comment]
Your text looks great and thanks for adding that!
