### ISSUE TITLE
Is it possible to generate glue code from an existing C++ header?

### ISSUE THREAD

**Issue by DominicCabral** [cross-language-cpp/djinni-generator#36]
I understand the approach according to documentation is to:

1. define you djinni file
2. generate hpp/objc/java
3. add cpp implementation 

But for my use case, I'd love to be able to:

1. given an existing C++ .h file
2. generate objc/java glue code

Is what I'm explaining currently possible?

**Comment by a4z** [comment]
Hi Dominic,
no, this is not possible.
You require either a djinni IDL file, or a yaml file in which you can define types that are not in the IDL language available.

But feeding in a header and magically get Java / ObjC bindings is not possible.

**Comment by DominicCabral** [comment]
Thanks for the quick response @a4z
