### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by canatella** [cross-language-cpp/djinni-generator#53]
Is there some interest in adding Rust support ? I have some part of my C++ code bases that I'd like to migrate to Rust and I think that Djinni and its interfaces would make a good and easy target for interop. What do you think ? 

Just some random idea, I'm not an expert in Djinni and even less in Rust but maybe first adding a C generator that creates an FFI  api. Then use that code to present the C++ implementation to the equivalent Rust interface and vice-versa. There is the problem of somehow respecting the `std::shared_ptr<>` lifetimes and probably a tons of other things I did not think about but I just want to spark a discussion and check for interest in this feature.

Thanks for maintaining this nice project!

**Comment by a4z** [comment]
Rust support, as some other languages, could work via the C bindings - or a variation of them - that are currently used for Python.
So the goal should be focus on the Python bindings, then evaluate what is possible to make with them, or what is missing for other languages.
Until this is done, having issues for language "InsertName" is not helpful, therefore I close this ticket for now to reduce the ticket noise.

**Comment by canatella** [comment]
Well that's a bit rough. The idea here was to collect what would be needed, how types could mapped, a having a general discussion. It feels to me that closing this is more about having a nice empty issue list than trying to move djinni forward...

**Comment by a4z** [comment]
Sorry to hear you feel like that, @canatella .
Please be assured that the idea for Rust bindings is not dead or ignored.

As mentioned, rust bindings can be archived via the C wrapper, and that is currently integrated.
If you want helping to move forward, please help testing that so it reaches a state it can be used for bindings other languages, like rust. 

If you want to discuss ideas, please feel free the join our slack developer channel, you can self register via the link mentioned on the documentation homepage.

**Comment by jothepro** [comment]
FYI @canatella we decided that instead of the issue tracker we want to promote [Github Discussions](https://github.com/cross-language-cpp/djinni-generator/discussions) as a place to collect & discuss ideas like yours, that need more refinement or that may not be super concrete yet.

Pls feel free to open a discussion there to share your ideas about Rust support! We care about building and maintaining an active community around Djinni, and we need your ideas & input for that! 😊
