### ISSUE TITLE
generated code doesn't compile

### ISSUE THREAD

**Issue by eakoli** [cross-language-cpp/djinni-generator#55]
Currently --objc-type-prefix is an optional objc argument. If this is left off the generated objc code will not compile as there are type collisions.

Even if you move the c++ types into a namespace (--cpp-namespace test) the collision still exists, as the generated code does not specify an explicit scope when referencing the objc classes.

```
user = record {
    id: i64;
    name: string;
}
```

this will generate the following 

```
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#import "User.h"
#include "user.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class User;

namespace djinni_generated {

struct User
{
    using CppType = ::test::User;
    using ObjcType = User*;

    using Boxed = User;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
```
```
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#import "User+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto User::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.id),
            ::djinni::String::toCpp(obj.name)};
}

auto User::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[User alloc] initWithId:(::djinni::I64::fromCpp(cpp.id))
                                   name:(::djinni::String::fromCpp(cpp.name))];
}

}  // namespace djinni_generated
```

As you can see `using ObjcType = User*;` references User in the current scope (which is the struct), the generated code should be `using ObjcType = ::User*;` to ensure that it references the objc class (which are always in the global scope)
The same issue occurs with ` using Boxed = User;` and the 'fromCpp' implementation.

Additionally in the generated implementation file the 'fromCpp' references the Objc class directly instead of using the type alias (ObjcType)

The generator should be updated to
a) reference objc types via the global scope
b) <type>::fromCpp should use the type alias (ObjcType) instead of the type directly
c) require at least one of --objc-type-prefix --cpp-namespace to ensure the generated code is compilable.

Additional suggestion:
use a decorator suffix for the generated converter classes (UserType, UserConverter) to further disambiguate the name collisions.

**Comment by a4z** [comment]
Hi Chris, thank you for the report!

I agree that, especially since there is a huge chance that types are forwarded into Swift, the 3 char prefix rule should not be enforced on users.

Your suggestions make sense, do you also want to implement them? 
If not, you need to wait a little bit until I , or someone else find the time to do it.
