### ISSUE TITLE
Test should clean up the result folder before running

### ISSUE THREAD

**Issue by a4z** [cross-language-cpp/djinni-generator#57]
Tests depend on what a test run generated into the it/resources/result folder.

But it is possible that there are files from previous runs, so tests on local machine require human intervention before running tests. 
It would be better to invalidate or remove all already existing files before a test is running

**Comment by jothepro** [comment]
That's definitely a good idea! 👍  I guess the best approach would be to simply delete all folders created in `src/it/resources/result` in the Integration-Test setup? I remember that I did not want to clean them up after the test execution for debugging purposes, but I really wonder why it never came to my mind to clean them up in the setup 🙈
