### ISSUE TITLE
Add documentation for cli usage & idl-format

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-generator#6]
As a user I want to get a quick overview in the Readme on how the CLI works & what the djinni-IDL is.

To be defined: Should the in-detail djinni-IDL documentation be in the main Readme like in the old repo, or should it be in a separate document, e.g. in a subfolder `/doc`?

**Comment by prsolucoes** [comment]
Hi,

Subfolder will be nice.

Thanks.

**Comment by jothepro** [comment]
Thanks for you feedback. :) We are currently planning to have a single website that pulls the documentation from all repositories related to djinni and displays it on one website: https://github.com/cross-language-cpp/djinni-documentation
More details can be found here: https://github.com/cross-language-cpp/djinni/issues/17

To make this work I will have to put all more detailed documentation in a subfolder. 
I'm closing this issue, the decision is already made.

Pls. be patient regarding the documentation, we are working on it (or at least think about it 😋 )

**Comment by jothepro** [comment]
Oops, the issue is about initially adding the docs at all, I need to reopen it. Sry for the confusion 🙈
