### ISSUE TITLE
Non-null pointers do not work when using modularization

### ISSUE THREAD

**Issue by roman-captural** [cross-language-cpp/djinni-generator#61]
Using non-null pointer types with the --cpp-nn-header argument together with modularization does not work properly.

Here’s a toy example:
a.djinni
```
a = interface +c {
    const test();
}
b = interface +c {
    const test(a: a): a;
}
```

c.djinni
```
@extern "a.yaml"
c = interface +c {
    const test(a: a): a;
}
```

run-djinni.sh
```
#! /usr/bin/env bash
set -e
module="$1"
base_dir=$(cd "`dirname "0"`" && pwd)
cpp_header_out="$base_dir/cpp/include/abc/$module"
cpp_src_out="$base_dir/cpp/src/$module"
namespace="abc"
djinni_file="$module.djinni"
djinni \
  --cpp-out $cpp_src_out \
  --cpp-header-out $cpp_header_out \
  --cpp-namespace $namespace \
  --cpp-nn-header "\"nn.hpp\"" \
  --cpp-nn-type "dropbox::oxygen::nn_shared_ptr" \
  --cpp-nn-check-expression "NN_CHECK_ASSERT" \
  --yaml-out . \
  --yaml-out-file ${module}.yaml \
  --idl $djinni_file
```

Executing `run-djinni.sh` for both modules `a` and `c` generates the three headers `a.hpp`, `b.hpp` and `c.hpp`:
```
./run-djinni.sh a
./run-djinni.sh c
```

cpp/include/abc/a/a.hpp
```
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from a.djinni
#pragma once
namespace abc {
class A {
public:
    virtual ~A() {}
    virtual void test() const = 0;
};
}  // namespace abc

```

cpp/include/abc/a/b.hpp
```
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from a.djinni
#pragma once
#include "nn.hpp"
#include <memory>
namespace abc {
class A;
class B {
public:
    virtual ~B() {}
    virtual dropbox::oxygen::nn_shared_ptr<A> test(const dropbox::oxygen::nn_shared_ptr<A> & a) const = 0;
};
}  // namespace abc
```

cpp/include/abc/c/c.hpp
```
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from c.djinni
#pragma once
#include "a.hpp"
#include <memory>
namespace abc {
class C {
public:
    virtual ~C() {}
    virtual std::shared_ptr<::abc::A> test(const std::shared_ptr<::abc::A> & a) const = 0;
};
}  // namespace abc
```
I think ```C::test``` should take and return a ```shared_ptr<A>``` rather than a ```nn_shared_ptr<A>```  just like ```B::test``` does.

**Comment by a4z** [comment]
Thanks a lot for reporting that issue! 
Great report!!

If you want to dig into the problem, please feel free to do so, we will support you as good as possible.

If you prefer waiting for us doing so, please be a little bit patience, it can take some time until some volunteer will find time to work on that issue.

**Comment by roman-captural** [comment]
@a4z I briefly looked into it today and I think I found a working solution. I will try later this week to add a unit test to make the change ready for a pull request.

**Comment by a4z** [comment]
Sounds awesome, looking forward seeing the improvement!

**Comment by a4z** [comment]
Wow , that was fast !  

This issue makes me start thinking if we should integrate the not null pointer from Doprbox, or any other implementation, into the support lib, so a default  is  just available for users.
