### ISSUE TITLE
Add deprecation warning for command line options that we plan to remove

### ISSUE THREAD

**Issue by a4z** [cross-language-cpp/djinni-generator#97]
As a learning from #96 

Since we plan to clean up the cli, we should have a way of making cli options and flag deprecated, so if they are used there will be a warning, and users have time to react on that situation, contacting us, explain use cases and let us find solutions together.
 
It would be nice if this could be a simple deprecate_option decorator for an option, so it's easy to reuse, but let's see

**Comment by jothepro** [comment]
I think thats a very good idea! 👍 Not directly related to this: There is a long overdue major update to the scopt library that requires some refactoring in the cli parameter parsing anyways. Maybe this issue would be a good incentive to finally do this, or explore if there is a feature like this in the latest scopt version?

**Comment by a4z** [comment]
Sounds good, can you please add an issue and link it to this one.
